Task 6
mgn200/imdb_movies pull request #2
Opened 2017-06-14 19:18 UTC by mgn200

2017-06-14 23:29 UTC, zverok requested changes

2017-06-14 23:29 UTC, zverok commented on ancient_movie.rb
> +    @price = 1
Тебе не кажется, что второе — это константа, а первое вообще можно из названия класса вычислить?

2017-06-14 23:29 UTC, zverok commented on movie.rb
> +  attr_accessor :list, :link, :title, :year, :country, :date, :genre,
А почему accessor? В целом, это обычно code smell, если тебе нужен accessor

2017-06-14 23:29 UTC, zverok commented on movie_collection.rb
> +      end
`case` и ranges тут намного лучше будут смотреться.

2017-06-14 23:29 UTC, zverok commented on netflix.rb
> +  attr_accessor :balance, :all
Почему `accessor`?

2017-06-14 23:29 UTC, zverok commented on netflix.rb
> +    @balance = 10
А почему с 10 начинаем? Подарок клиенту? :)

2017-06-14 23:29 UTC, zverok commented on netflix.rb
> +  def initialize(collection)
Ээээ погодь. Одно из двух. Или мы наследуемся от `MovieCollection`, или храним её внутри нашего кинотеатра. А наследоваться И хранить внутри — ?...

2017-06-14 23:29 UTC, zverok commented on netflix.rb
> +    super
Чтобы что???

2017-06-14 23:29 UTC, zverok commented on theatre.rb
> +  end
Эти два метода пользуются одинаковыми данными, но при этом они дублируют все эти данные. Как-то обобщить бы, м?

2017-06-14 23:29 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  end
1. Посмотри на betterspecs.org внимательно. Мы можем здесь например определить `subject` — субъект тестирования (наше кино). Можно тогда например делать так: `it { is_expected.to have_attributes(price: 1) }`
2. А ещё можно гем `rspec-its` использовать, тогда можно так: `its(:price) { is_expected.to eq 1 }`

В целом, мы сейчас стараемся писать очень-очень короткие тесты, максимально выражающие смысл (без потери читабельности)

2017-06-14 23:29 UTC, zverok commented on spec/factories.rb
> +FactoryGirl.define do
А правда без `factory_girl` тут никак?
По-моему, совершеннейший оверкилл.

2017-06-14 23:29 UTC, zverok commented on spec/movie_collection_spec.rb
> +  mc_test = MovieCollection.new('movies_for_spec')
Почему так?.. У нас бывает `let` и `subject` для этих дел. Они хороши тем, что в отличие от твоего кода, реинициализируются для каждого нового теста.

2017-06-14 23:29 UTC, zverok commented on spec/movie_collection_spec.rb
> +      expect(mc_test.all.first.is_a? ModernMovie).to be true
`expect(mc_test.all.first).to be_a ModernMovie`, хотя бы уж.

2017-06-14 23:29 UTC, zverok commented on spec/movie_collection_spec.rb
> +    end
Но в целом лучше бы как-то более обобщённо.

2017-06-14 23:29 UTC, zverok commented on spec/netflix_spec.rb
> +  end
Это что тестирует? И почему описание такое странное?..

2017-06-14 23:29 UTC, zverok commented on spec/netflix_spec.rb
> +      end
Это имеет смысл например вот так делать:
```ruby
subject { netflix.show(params) }
context 'Ancient' do
  let(:params) { {period: 'Classic'} }
  it { expect { subject }.to change(netflix, :balance).by -1.5 }
end
```
Всё в целом, надеюсь, понятно — а `change(netflix, :balance)` лучше чем `change { netflix.balance }` из-за документируемости. Если ты попробуешь вызвать `rspec --format doc`, увидишь разницу.

2017-06-14 23:29 UTC, zverok commented on spec/netflix_spec.rb
> +        expect { netflix_no_balance.show(period: 'Ancient') }.to raise_error
То есть успешность этого теста зависит от того, в каком порядке их вызывали?.. Это очень-очень плохо. Тесты должны быть независимые, иначе баг в одном тесте сломает другой тест и ты отладишь это ровно никогда.

2017-06-14 23:29 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(netflix.how_much? 'NewMovie').to eq 5
Вроде по заданию — по названию должно отвечать же.
И хорошо бы протестировать что происходит если название неизвестное.

2017-06-14 23:29 UTC, zverok commented on spec/theatre_spec.rb
> +      end
вынести правильные `let`ы и `subject`ы, так чтобы тесты выглядели как 
`it { is_expected.to have_attributes(period: 'Ancient') }`

2017-06-14 23:29 UTC, zverok commented on spec/theatre_spec.rb
> +    end
А как насчёт периода времени, когда никакого кина не показывают?

2017-06-14 23:29 UTC, zverok commented on spec/theatre_spec.rb
> +          expect(theatre.show('10:04')).to eq "AncientMovie will be shown at 10:04"
Кстати, по заданию было не возвращать, а _печатать_ эту строчку.

2017-06-23 22:05 UTC, zverok requested changes

2017-06-23 22:05 UTC, zverok commented on ancient_movie.rb
> +  end
если он ТОЛЬКО вызывает super, зачем вообще этот метод переопределять?

2017-06-23 22:05 UTC, zverok commented on ancient_movie.rb
> +  end
Это можно один раз в классе `Movie` сделать.

2017-06-23 22:05 UTC, zverok commented on movie.rb
> +  attr_accessor :list, :link, :title, :year, :country, :date, :genre,
Почему `accessor`?.. Чтобы что?

2017-06-23 22:05 UTC, zverok commented on movie.rb
> +    @period = self.class.name.match(/(\w+)Movie/)[1].to_s.downcase.to_sym
Достаточно метода, зачем это хранить в переменной?..

2017-06-23 22:05 UTC, zverok commented on movie.rb
> +    end
хм, а это откуда/зачем?.. если нужно — оно же не контролирует наличия такого жанра в списке, напр. и некрасивенько в целом.

2017-06-23 22:05 UTC, zverok commented on movie_collection.rb
> +      end
тут диапазоны (ranges) будут красивше

2017-06-23 22:05 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  subject(:ancient_movie) { MovieCollection.new('movies.txt').filter(period: :ancient).sample }
лучше бы независимый (от коллекции) тест, только этот класс тестирующий.

2017-06-23 22:05 UTC, zverok commented on spec/ancient_movie_spec.rb
> +      expect { ancient_movie.to_s }.to output("#{ancient_movie.title} - старый фильм(#{ancient_movie.year} год)").to_stdout
кстати, нет, не печатать — просто возвращать строку должно.

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +  netflix.pay 25
Нехорошо. `let` и `before` наши друзья.
Иначе у тебя этот код выполняется ОДИН раз (при определении тестов), и получаетяс что тесты взаимозависимы (типа смотря в каком порядке выполнятся, они могут съесть эти деньги или нет)

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +          it { expect { subject }.to change(netflix, :balance).by -1 }
...и что-то напечатать, м?..

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +      end
...и что-то сделать предсказуемое при некорректных фильтрах, ненайденном фильме и т.д.?..

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +      it { expect { subject }.to raise_error }
...а какую именно и с каким сообщением? :)

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +      before { netflix.pay -25 }
Кстати, «заплатить отрицательную сумму» по логике должно бы быть невозможно, и даже тест на это должен быть!

2017-06-23 22:05 UTC, zverok commented on spec/netflix_spec.rb
> +    it { is_expected.to eq 5 }
А если фильм не найден?.. А если у фильма другая цена?

2017-06-23 22:05 UTC, zverok commented on spec/theatre_spec.rb
> +        title = movies.filter(period: :ancient).first.title
это ж бы наверное `let` должен быть?..

2017-06-23 22:05 UTC, zverok commented on spec/theatre_spec.rb
> +        expect(theatre.when? title).to eq "06:00".."12:00"
а это — `subject`

2017-06-23 22:05 UTC, zverok commented on spec/theatre_spec.rb
> +      it { is_expected.to be_a String }
Правда?.. А что этот тест тестирует?..
Я могу написать метод который его (и следующие) проходит! Он будет выглядеть так:
```ruby
def show(*)
  'понятия не имею что тут происходит'
end
```
ХОРОШИЙ тест проходит только правильная реализация, а неправильная не проходит.

2017-06-23 22:05 UTC, zverok commented on spec/theatre_spec.rb
> +  describe '#when?' do
/me смотрит подозрительно
кажется, это второй `describe` того же метода?..

2017-06-23 22:05 UTC, zverok commented on theatre.rb
> +    end
По-моему этот и предыдущий метод повторяют одни и те же данные (какому времени дня соответствует какой фильтр) два раза независимо. А вот бы это знание в константы вынести и сделать используемым в обоих методах, м?

2017-06-26 20:15 UTC, zverok requested changes

2017-06-26 20:15 UTC, zverok commented on movie.rb
> +    PRICES[self.period]
а зачем тогда константа `PRICE` в каждом фильме?..

2017-06-26 20:15 UTC, zverok commented on spec/ancient_movie_spec.rb
> +               }
а почему не в `let`, в чём идея?

2017-06-26 20:15 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  end
В принципе это всё можно укоротить до:
```ruby
it {
  is_expected.to have_attributes(price: 1, period: :ancient, to_s: "...")
}
```
...не то чтобы обязательно именно так, но спеки, чтобы не задолбали своим написанием, лучше бы делать как можно короче. 
И ещё — лучше проверочную строку делать явной, без использования проверяемой переменной (а то два бага могут спрятать друг друга — если скажем `#title` окажется пустой строкой, то в таком тесте никто этого не заметит, а в тесте `.to eq "Test movie - ...."` заметит)

2017-06-26 20:15 UTC, zverok commented on spec/movie_collection_spec.rb
> +    subject { movie_collection.pick_movie(random_movie_arr) }
если `random_movie_arr` используется только тут, то тут (внутри этого дескрайба) его и надо описывать. 
но, кстати, что тестирует этот тест?..

2017-06-26 20:15 UTC, zverok commented on spec/netflix_spec.rb
> +      end
↑ этот коммент всё ещё актуален.

2017-06-26 20:15 UTC, zverok commented on spec/netflix_spec.rb
> +      subject { netflix_zero_balance.show(params) }
Я бы сказал, что вместо создания другого нетфликса, лучше бы в стр.4 написать `before { netflix.pay(prepayment) }`, определить `let(:prepayment) { 10 }`, а здесь — переопределить как 0

2017-06-26 20:15 UTC, zverok commented on spec/spec_helper.rb
> +=end
убей всё лишнее :)

2017-06-26 20:15 UTC, zverok commented on theatre.rb
> +  end
Не, эти методы должны быть проще (не должны знать о том что там в константе `SCHEDULE` вообще — если в ней станет 8 разных периодов или поменяются фильтры, должны продолжать работать)

2017-06-27 15:53 UTC, mgn200 commented on movie.rb
> +    PRICES[self.period]
забыл их убрать

2017-06-27 15:55 UTC, mgn200 commented on spec/ancient_movie_spec.rb
> +               }
я подумал зачем let, если тест маленький и используются эти переменны только в одноим месте и не важно что они инициализируются один раз и навсегда для всех примеров

2017-06-27 16:41 UTC, mgn200 commented on spec/movie_collection_spec.rb
> +    subject { movie_collection.pick_movie(random_movie_arr) }
судя по всему просто что он хотя бы фильм возвращает)

2017-06-28 09:50 UTC, zverok commented on spec/ancient_movie_spec.rb
> +               }
ну ты всегда имеешь опасность, что какой-нибудь тест (по ошибке или ради тестирования специальной фичи какой-нибудь) поменяет в этой переменной `:date` — и это повлияет на ВСЕ остальные тесты. Важная фича `let` — что оно инициализируется заново для каждого теста, делая их независимыми друг от друга.

2017-06-28 17:54 UTC, mgn200 commented on theatre.rb
> +  end
переписал в след. коммите, но мне кажется усложнил код

2017-06-29 17:02 UTC, mgn200 commented on spec/netflix_spec.rb
> +      end
Чуть ниже тестируются неверные параметры и нехватка баланса

2017-07-01 10:48 UTC, zverok reviewed
Вообще уже очень хорошо получилось, компактно и мощно. :+1:

2017-07-01 10:48 UTC, zverok commented on spec/theatre_spec.rb
> +    end
А то, что он кино правильного типа покажет, надо бы тоже потестировать, м?

2017-07-01 10:48 UTC, zverok commented on theatre.rb
> +      v.select { |x, y| movie.matches? x, y }.any?
`select {}.any?` — проще записать вот так: `any? { тот же блок с проверкой }`, будет работать :)
Ну и переменные в этих блоках я бы назвал чуть понятнее, сам же запутаешься, если вдруг к этому коду через неделю придётся вернуться.

2017-07-01 19:20 UTC, mgn200 commented on theatre.rb
> +      v.select { |x, y| movie.matches? x, y }.any?
done

2017-07-01 19:28 UTC, zverok approved these changes
Отлично. Надеюсь, тебе тоже нравится, как оно получается.

2017-07-01 19:39 UTC, merged